[ask_price__field_rolling_cmpopenclose__5m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose.5m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.5m",]

[ask_price__field_rolling_cmpopenclose__10m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose.10m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.10m",]

[ask_price__field_rolling_cmpopenclose__15m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose.15m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.15m",]

[ask_price__field_rolling_cmpopenclose__20m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose.20m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.20m",]

[ask_price__field_rolling_cmpopenclose__25m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose.25m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.25m",]

[ask_price__field_rolling_cmpopenclose__30m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose.30m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.30m",]

[ask_price__field_rolling_cmpopenclose__35m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose.35m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.35m",]

[ask_price__field_rolling_cmpopenclose__40m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose.40m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.40m",]

[ask_price__field_rolling_cmpopenclose__45m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose.45m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.45m",]

[ask_price__field_rolling_cmpopenclose__50m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose.50m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.50m",]

[ask_price__field_rolling_cmpopenclose__55m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose.55m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.55m",]

[ask_price__field_rolling_cmpopenclose__60m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose", "@ask_price.field_rolling_cmpopenclose.60m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.60m",]

[bid_price__field_rolling_cmpopenclose__5m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose.5m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.5m",]

[bid_price__field_rolling_cmpopenclose__10m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose.10m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.10m",]

[bid_price__field_rolling_cmpopenclose__15m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose.15m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.15m",]

[bid_price__field_rolling_cmpopenclose__20m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose.20m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.20m",]

[bid_price__field_rolling_cmpopenclose__25m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose.25m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.25m",]

[bid_price__field_rolling_cmpopenclose__30m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose.30m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.30m",]

[bid_price__field_rolling_cmpopenclose__35m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose.35m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.35m",]

[bid_price__field_rolling_cmpopenclose__40m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose.40m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.40m",]

[bid_price__field_rolling_cmpopenclose__45m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose.45m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.45m",]

[bid_price__field_rolling_cmpopenclose__50m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose.50m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.50m",]

[bid_price__field_rolling_cmpopenclose__55m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose.55m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.55m",]

[bid_price__field_rolling_cmpopenclose__60m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose", "@bid_price.field_rolling_cmpopenclose.60m", "@price.field_rolling_cmpopenclose", "@price.field_rolling_cmpopenclose.60m",]

[bid_qty__field_rolling_cmpopenclose__5m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose.5m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.5m",]

[bid_qty__field_rolling_cmpopenclose__10m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose.10m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.10m",]

[bid_qty__field_rolling_cmpopenclose__15m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose.15m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.15m",]

[bid_qty__field_rolling_cmpopenclose__20m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose.20m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.20m",]

[bid_qty__field_rolling_cmpopenclose__25m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose.25m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.25m",]

[bid_qty__field_rolling_cmpopenclose__30m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose.30m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.30m",]

[bid_qty__field_rolling_cmpopenclose__35m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose.35m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.35m",]

[bid_qty__field_rolling_cmpopenclose__40m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose.40m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.40m",]

[bid_qty__field_rolling_cmpopenclose__45m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose.45m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.45m",]

[bid_qty__field_rolling_cmpopenclose__50m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose.50m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.50m",]

[bid_qty__field_rolling_cmpopenclose__55m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose.55m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.55m",]

[bid_qty__field_rolling_cmpopenclose__60m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose", "@bid_qty.field_rolling_cmpopenclose.60m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.60m",]

[ask_qty__field_rolling_cmpopenclose__5m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose.5m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.5m",]

[ask_qty__field_rolling_cmpopenclose__10m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose.10m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.10m",]

[ask_qty__field_rolling_cmpopenclose__15m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose.15m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.15m",]

[ask_qty__field_rolling_cmpopenclose__20m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose.20m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.20m",]

[ask_qty__field_rolling_cmpopenclose__25m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose.25m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.25m",]

[ask_qty__field_rolling_cmpopenclose__30m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose.30m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.30m",]

[ask_qty__field_rolling_cmpopenclose__35m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose.35m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.35m",]

[ask_qty__field_rolling_cmpopenclose__40m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose.40m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.40m",]

[ask_qty__field_rolling_cmpopenclose__45m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose.45m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.45m",]

[ask_qty__field_rolling_cmpopenclose__50m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose.50m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.50m",]

[ask_qty__field_rolling_cmpopenclose__55m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose.55m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.55m",]

[ask_qty__field_rolling_cmpopenclose__60m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_cmpopenclose"
tags = [ "@field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose", "@ask_qty.field_rolling_cmpopenclose.60m", "@qty.field_rolling_cmpopenclose", "@qty.field_rolling_cmpopenclose.60m",]

[ask_price__field_rolling_cmpopenclose__5m.params]
window = "300s"

[ask_price__field_rolling_cmpopenclose__10m.params]
window = "600s"

[ask_price__field_rolling_cmpopenclose__15m.params]
window = "900s"

[ask_price__field_rolling_cmpopenclose__20m.params]
window = "1200s"

[ask_price__field_rolling_cmpopenclose__25m.params]
window = "1500s"

[ask_price__field_rolling_cmpopenclose__30m.params]
window = "1800s"

[ask_price__field_rolling_cmpopenclose__35m.params]
window = "2100s"

[ask_price__field_rolling_cmpopenclose__40m.params]
window = "2400s"

[ask_price__field_rolling_cmpopenclose__45m.params]
window = "2700s"

[ask_price__field_rolling_cmpopenclose__50m.params]
window = "3000s"

[ask_price__field_rolling_cmpopenclose__55m.params]
window = "3300s"

[ask_price__field_rolling_cmpopenclose__60m.params]
window = "3600s"

[bid_price__field_rolling_cmpopenclose__5m.params]
window = "300s"

[bid_price__field_rolling_cmpopenclose__10m.params]
window = "600s"

[bid_price__field_rolling_cmpopenclose__15m.params]
window = "900s"

[bid_price__field_rolling_cmpopenclose__20m.params]
window = "1200s"

[bid_price__field_rolling_cmpopenclose__25m.params]
window = "1500s"

[bid_price__field_rolling_cmpopenclose__30m.params]
window = "1800s"

[bid_price__field_rolling_cmpopenclose__35m.params]
window = "2100s"

[bid_price__field_rolling_cmpopenclose__40m.params]
window = "2400s"

[bid_price__field_rolling_cmpopenclose__45m.params]
window = "2700s"

[bid_price__field_rolling_cmpopenclose__50m.params]
window = "3000s"

[bid_price__field_rolling_cmpopenclose__55m.params]
window = "3300s"

[bid_price__field_rolling_cmpopenclose__60m.params]
window = "3600s"

[bid_qty__field_rolling_cmpopenclose__5m.params]
window = "300s"

[bid_qty__field_rolling_cmpopenclose__10m.params]
window = "600s"

[bid_qty__field_rolling_cmpopenclose__15m.params]
window = "900s"

[bid_qty__field_rolling_cmpopenclose__20m.params]
window = "1200s"

[bid_qty__field_rolling_cmpopenclose__25m.params]
window = "1500s"

[bid_qty__field_rolling_cmpopenclose__30m.params]
window = "1800s"

[bid_qty__field_rolling_cmpopenclose__35m.params]
window = "2100s"

[bid_qty__field_rolling_cmpopenclose__40m.params]
window = "2400s"

[bid_qty__field_rolling_cmpopenclose__45m.params]
window = "2700s"

[bid_qty__field_rolling_cmpopenclose__50m.params]
window = "3000s"

[bid_qty__field_rolling_cmpopenclose__55m.params]
window = "3300s"

[bid_qty__field_rolling_cmpopenclose__60m.params]
window = "3600s"

[ask_qty__field_rolling_cmpopenclose__5m.params]
window = "300s"

[ask_qty__field_rolling_cmpopenclose__10m.params]
window = "600s"

[ask_qty__field_rolling_cmpopenclose__15m.params]
window = "900s"

[ask_qty__field_rolling_cmpopenclose__20m.params]
window = "1200s"

[ask_qty__field_rolling_cmpopenclose__25m.params]
window = "1500s"

[ask_qty__field_rolling_cmpopenclose__30m.params]
window = "1800s"

[ask_qty__field_rolling_cmpopenclose__35m.params]
window = "2100s"

[ask_qty__field_rolling_cmpopenclose__40m.params]
window = "2400s"

[ask_qty__field_rolling_cmpopenclose__45m.params]
window = "2700s"

[ask_qty__field_rolling_cmpopenclose__50m.params]
window = "3000s"

[ask_qty__field_rolling_cmpopenclose__55m.params]
window = "3300s"

[ask_qty__field_rolling_cmpopenclose__60m.params]
window = "3600s"
