[ask_price__field_rolling_diffopenclose__5m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose.5m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.5m",]

[ask_price__field_rolling_diffopenclose__10m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose.10m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.10m",]

[ask_price__field_rolling_diffopenclose__15m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose.15m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.15m",]

[ask_price__field_rolling_diffopenclose__20m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose.20m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.20m",]

[ask_price__field_rolling_diffopenclose__25m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose.25m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.25m",]

[ask_price__field_rolling_diffopenclose__30m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose.30m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.30m",]

[ask_price__field_rolling_diffopenclose__35m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose.35m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.35m",]

[ask_price__field_rolling_diffopenclose__40m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose.40m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.40m",]

[ask_price__field_rolling_diffopenclose__45m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose.45m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.45m",]

[ask_price__field_rolling_diffopenclose__50m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose.50m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.50m",]

[ask_price__field_rolling_diffopenclose__55m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose.55m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.55m",]

[ask_price__field_rolling_diffopenclose__60m]
columns = [ "ask_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose", "@ask_price.field_rolling_diffopenclose.60m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.60m",]

[bid_price__field_rolling_diffopenclose__5m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose.5m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.5m",]

[bid_price__field_rolling_diffopenclose__10m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose.10m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.10m",]

[bid_price__field_rolling_diffopenclose__15m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose.15m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.15m",]

[bid_price__field_rolling_diffopenclose__20m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose.20m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.20m",]

[bid_price__field_rolling_diffopenclose__25m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose.25m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.25m",]

[bid_price__field_rolling_diffopenclose__30m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose.30m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.30m",]

[bid_price__field_rolling_diffopenclose__35m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose.35m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.35m",]

[bid_price__field_rolling_diffopenclose__40m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose.40m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.40m",]

[bid_price__field_rolling_diffopenclose__45m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose.45m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.45m",]

[bid_price__field_rolling_diffopenclose__50m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose.50m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.50m",]

[bid_price__field_rolling_diffopenclose__55m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose.55m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.55m",]

[bid_price__field_rolling_diffopenclose__60m]
columns = [ "bid_price",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose", "@bid_price.field_rolling_diffopenclose.60m", "@price.field_rolling_diffopenclose", "@price.field_rolling_diffopenclose.60m",]

[bid_qty__field_rolling_diffopenclose__5m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose.5m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.5m",]

[bid_qty__field_rolling_diffopenclose__10m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose.10m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.10m",]

[bid_qty__field_rolling_diffopenclose__15m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose.15m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.15m",]

[bid_qty__field_rolling_diffopenclose__20m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose.20m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.20m",]

[bid_qty__field_rolling_diffopenclose__25m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose.25m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.25m",]

[bid_qty__field_rolling_diffopenclose__30m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose.30m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.30m",]

[bid_qty__field_rolling_diffopenclose__35m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose.35m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.35m",]

[bid_qty__field_rolling_diffopenclose__40m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose.40m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.40m",]

[bid_qty__field_rolling_diffopenclose__45m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose.45m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.45m",]

[bid_qty__field_rolling_diffopenclose__50m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose.50m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.50m",]

[bid_qty__field_rolling_diffopenclose__55m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose.55m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.55m",]

[bid_qty__field_rolling_diffopenclose__60m]
columns = [ "bid_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose", "@bid_qty.field_rolling_diffopenclose.60m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.60m",]

[ask_qty__field_rolling_diffopenclose__5m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose.5m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.5m",]

[ask_qty__field_rolling_diffopenclose__10m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose.10m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.10m",]

[ask_qty__field_rolling_diffopenclose__15m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose.15m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.15m",]

[ask_qty__field_rolling_diffopenclose__20m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose.20m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.20m",]

[ask_qty__field_rolling_diffopenclose__25m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose.25m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.25m",]

[ask_qty__field_rolling_diffopenclose__30m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose.30m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.30m",]

[ask_qty__field_rolling_diffopenclose__35m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose.35m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.35m",]

[ask_qty__field_rolling_diffopenclose__40m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose.40m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.40m",]

[ask_qty__field_rolling_diffopenclose__45m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose.45m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.45m",]

[ask_qty__field_rolling_diffopenclose__50m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose.50m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.50m",]

[ask_qty__field_rolling_diffopenclose__55m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose.55m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.55m",]

[ask_qty__field_rolling_diffopenclose__60m]
columns = [ "ask_qty",]
module = "features.scripts.field_rolling_diffopenclose"
tags = [ "@field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose", "@ask_qty.field_rolling_diffopenclose.60m", "@qty.field_rolling_diffopenclose", "@qty.field_rolling_diffopenclose.60m",]

[ask_price__field_rolling_diffopenclose__5m.params]
window = "300s"

[ask_price__field_rolling_diffopenclose__10m.params]
window = "600s"

[ask_price__field_rolling_diffopenclose__15m.params]
window = "900s"

[ask_price__field_rolling_diffopenclose__20m.params]
window = "1200s"

[ask_price__field_rolling_diffopenclose__25m.params]
window = "1500s"

[ask_price__field_rolling_diffopenclose__30m.params]
window = "1800s"

[ask_price__field_rolling_diffopenclose__35m.params]
window = "2100s"

[ask_price__field_rolling_diffopenclose__40m.params]
window = "2400s"

[ask_price__field_rolling_diffopenclose__45m.params]
window = "2700s"

[ask_price__field_rolling_diffopenclose__50m.params]
window = "3000s"

[ask_price__field_rolling_diffopenclose__55m.params]
window = "3300s"

[ask_price__field_rolling_diffopenclose__60m.params]
window = "3600s"

[bid_price__field_rolling_diffopenclose__5m.params]
window = "300s"

[bid_price__field_rolling_diffopenclose__10m.params]
window = "600s"

[bid_price__field_rolling_diffopenclose__15m.params]
window = "900s"

[bid_price__field_rolling_diffopenclose__20m.params]
window = "1200s"

[bid_price__field_rolling_diffopenclose__25m.params]
window = "1500s"

[bid_price__field_rolling_diffopenclose__30m.params]
window = "1800s"

[bid_price__field_rolling_diffopenclose__35m.params]
window = "2100s"

[bid_price__field_rolling_diffopenclose__40m.params]
window = "2400s"

[bid_price__field_rolling_diffopenclose__45m.params]
window = "2700s"

[bid_price__field_rolling_diffopenclose__50m.params]
window = "3000s"

[bid_price__field_rolling_diffopenclose__55m.params]
window = "3300s"

[bid_price__field_rolling_diffopenclose__60m.params]
window = "3600s"

[bid_qty__field_rolling_diffopenclose__5m.params]
window = "300s"

[bid_qty__field_rolling_diffopenclose__10m.params]
window = "600s"

[bid_qty__field_rolling_diffopenclose__15m.params]
window = "900s"

[bid_qty__field_rolling_diffopenclose__20m.params]
window = "1200s"

[bid_qty__field_rolling_diffopenclose__25m.params]
window = "1500s"

[bid_qty__field_rolling_diffopenclose__30m.params]
window = "1800s"

[bid_qty__field_rolling_diffopenclose__35m.params]
window = "2100s"

[bid_qty__field_rolling_diffopenclose__40m.params]
window = "2400s"

[bid_qty__field_rolling_diffopenclose__45m.params]
window = "2700s"

[bid_qty__field_rolling_diffopenclose__50m.params]
window = "3000s"

[bid_qty__field_rolling_diffopenclose__55m.params]
window = "3300s"

[bid_qty__field_rolling_diffopenclose__60m.params]
window = "3600s"

[ask_qty__field_rolling_diffopenclose__5m.params]
window = "300s"

[ask_qty__field_rolling_diffopenclose__10m.params]
window = "600s"

[ask_qty__field_rolling_diffopenclose__15m.params]
window = "900s"

[ask_qty__field_rolling_diffopenclose__20m.params]
window = "1200s"

[ask_qty__field_rolling_diffopenclose__25m.params]
window = "1500s"

[ask_qty__field_rolling_diffopenclose__30m.params]
window = "1800s"

[ask_qty__field_rolling_diffopenclose__35m.params]
window = "2100s"

[ask_qty__field_rolling_diffopenclose__40m.params]
window = "2400s"

[ask_qty__field_rolling_diffopenclose__45m.params]
window = "2700s"

[ask_qty__field_rolling_diffopenclose__50m.params]
window = "3000s"

[ask_qty__field_rolling_diffopenclose__55m.params]
window = "3300s"

[ask_qty__field_rolling_diffopenclose__60m.params]
window = "3600s"
