[profit_300__profit_rolling_coeff__5m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_300", "@profit_rolling_coeff", "@profit_rolling_coeff.5m", "@profit_300.profit_rolling_coeff", "@profit_300.profit_rolling_coeff.5m",]

[profit_600__profit_rolling_coeff__5m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_600", "@profit_rolling_coeff", "@profit_rolling_coeff.5m", "@profit_600.profit_rolling_coeff", "@profit_600.profit_rolling_coeff.5m",]

[profit_1200__profit_rolling_coeff__5m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_1200", "@profit_rolling_coeff", "@profit_rolling_coeff.5m", "@profit_1200.profit_rolling_coeff", "@profit_1200.profit_rolling_coeff.5m",]

[profit_300__profit_rolling_coeff__10m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_300", "@profit_rolling_coeff", "@profit_rolling_coeff.10m", "@profit_300.profit_rolling_coeff", "@profit_300.profit_rolling_coeff.10m",]

[profit_600__profit_rolling_coeff__10m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_600", "@profit_rolling_coeff", "@profit_rolling_coeff.10m", "@profit_600.profit_rolling_coeff", "@profit_600.profit_rolling_coeff.10m",]

[profit_1200__profit_rolling_coeff__10m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_1200", "@profit_rolling_coeff", "@profit_rolling_coeff.10m", "@profit_1200.profit_rolling_coeff", "@profit_1200.profit_rolling_coeff.10m",]

[profit_300__profit_rolling_coeff__15m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_300", "@profit_rolling_coeff", "@profit_rolling_coeff.15m", "@profit_300.profit_rolling_coeff", "@profit_300.profit_rolling_coeff.15m",]

[profit_600__profit_rolling_coeff__15m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_600", "@profit_rolling_coeff", "@profit_rolling_coeff.15m", "@profit_600.profit_rolling_coeff", "@profit_600.profit_rolling_coeff.15m",]

[profit_1200__profit_rolling_coeff__15m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_1200", "@profit_rolling_coeff", "@profit_rolling_coeff.15m", "@profit_1200.profit_rolling_coeff", "@profit_1200.profit_rolling_coeff.15m",]

[profit_300__profit_rolling_coeff__20m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_300", "@profit_rolling_coeff", "@profit_rolling_coeff.20m", "@profit_300.profit_rolling_coeff", "@profit_300.profit_rolling_coeff.20m",]

[profit_600__profit_rolling_coeff__20m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_600", "@profit_rolling_coeff", "@profit_rolling_coeff.20m", "@profit_600.profit_rolling_coeff", "@profit_600.profit_rolling_coeff.20m",]

[profit_1200__profit_rolling_coeff__20m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_1200", "@profit_rolling_coeff", "@profit_rolling_coeff.20m", "@profit_1200.profit_rolling_coeff", "@profit_1200.profit_rolling_coeff.20m",]

[profit_300__profit_rolling_coeff__25m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_300", "@profit_rolling_coeff", "@profit_rolling_coeff.25m", "@profit_300.profit_rolling_coeff", "@profit_300.profit_rolling_coeff.25m",]

[profit_600__profit_rolling_coeff__25m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_600", "@profit_rolling_coeff", "@profit_rolling_coeff.25m", "@profit_600.profit_rolling_coeff", "@profit_600.profit_rolling_coeff.25m",]

[profit_1200__profit_rolling_coeff__25m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_1200", "@profit_rolling_coeff", "@profit_rolling_coeff.25m", "@profit_1200.profit_rolling_coeff", "@profit_1200.profit_rolling_coeff.25m",]

[profit_300__profit_rolling_coeff__30m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_300", "@profit_rolling_coeff", "@profit_rolling_coeff.30m", "@profit_300.profit_rolling_coeff", "@profit_300.profit_rolling_coeff.30m",]

[profit_600__profit_rolling_coeff__30m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_600", "@profit_rolling_coeff", "@profit_rolling_coeff.30m", "@profit_600.profit_rolling_coeff", "@profit_600.profit_rolling_coeff.30m",]

[profit_1200__profit_rolling_coeff__30m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_1200", "@profit_rolling_coeff", "@profit_rolling_coeff.30m", "@profit_1200.profit_rolling_coeff", "@profit_1200.profit_rolling_coeff.30m",]

[profit_300__profit_rolling_coeff__35m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_300", "@profit_rolling_coeff", "@profit_rolling_coeff.35m", "@profit_300.profit_rolling_coeff", "@profit_300.profit_rolling_coeff.35m",]

[profit_600__profit_rolling_coeff__35m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_600", "@profit_rolling_coeff", "@profit_rolling_coeff.35m", "@profit_600.profit_rolling_coeff", "@profit_600.profit_rolling_coeff.35m",]

[profit_1200__profit_rolling_coeff__35m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_1200", "@profit_rolling_coeff", "@profit_rolling_coeff.35m", "@profit_1200.profit_rolling_coeff", "@profit_1200.profit_rolling_coeff.35m",]

[profit_300__profit_rolling_coeff__40m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_300", "@profit_rolling_coeff", "@profit_rolling_coeff.40m", "@profit_300.profit_rolling_coeff", "@profit_300.profit_rolling_coeff.40m",]

[profit_600__profit_rolling_coeff__40m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_600", "@profit_rolling_coeff", "@profit_rolling_coeff.40m", "@profit_600.profit_rolling_coeff", "@profit_600.profit_rolling_coeff.40m",]

[profit_1200__profit_rolling_coeff__40m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_1200", "@profit_rolling_coeff", "@profit_rolling_coeff.40m", "@profit_1200.profit_rolling_coeff", "@profit_1200.profit_rolling_coeff.40m",]

[profit_300__profit_rolling_coeff__45m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_300", "@profit_rolling_coeff", "@profit_rolling_coeff.45m", "@profit_300.profit_rolling_coeff", "@profit_300.profit_rolling_coeff.45m",]

[profit_600__profit_rolling_coeff__45m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_600", "@profit_rolling_coeff", "@profit_rolling_coeff.45m", "@profit_600.profit_rolling_coeff", "@profit_600.profit_rolling_coeff.45m",]

[profit_1200__profit_rolling_coeff__45m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_1200", "@profit_rolling_coeff", "@profit_rolling_coeff.45m", "@profit_1200.profit_rolling_coeff", "@profit_1200.profit_rolling_coeff.45m",]

[profit_300__profit_rolling_coeff__50m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_300", "@profit_rolling_coeff", "@profit_rolling_coeff.50m", "@profit_300.profit_rolling_coeff", "@profit_300.profit_rolling_coeff.50m",]

[profit_600__profit_rolling_coeff__50m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_600", "@profit_rolling_coeff", "@profit_rolling_coeff.50m", "@profit_600.profit_rolling_coeff", "@profit_600.profit_rolling_coeff.50m",]

[profit_1200__profit_rolling_coeff__50m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_1200", "@profit_rolling_coeff", "@profit_rolling_coeff.50m", "@profit_1200.profit_rolling_coeff", "@profit_1200.profit_rolling_coeff.50m",]

[profit_300__profit_rolling_coeff__55m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_300", "@profit_rolling_coeff", "@profit_rolling_coeff.55m", "@profit_300.profit_rolling_coeff", "@profit_300.profit_rolling_coeff.55m",]

[profit_600__profit_rolling_coeff__55m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_600", "@profit_rolling_coeff", "@profit_rolling_coeff.55m", "@profit_600.profit_rolling_coeff", "@profit_600.profit_rolling_coeff.55m",]

[profit_1200__profit_rolling_coeff__55m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_1200", "@profit_rolling_coeff", "@profit_rolling_coeff.55m", "@profit_1200.profit_rolling_coeff", "@profit_1200.profit_rolling_coeff.55m",]

[profit_300__profit_rolling_coeff__60m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_300", "@profit_rolling_coeff", "@profit_rolling_coeff.60m", "@profit_300.profit_rolling_coeff", "@profit_300.profit_rolling_coeff.60m",]

[profit_600__profit_rolling_coeff__60m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_600", "@profit_rolling_coeff", "@profit_rolling_coeff.60m", "@profit_600.profit_rolling_coeff", "@profit_600.profit_rolling_coeff.60m",]

[profit_1200__profit_rolling_coeff__60m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_coeff"
tags = [ "@profit_1200", "@profit_rolling_coeff", "@profit_rolling_coeff.60m", "@profit_1200.profit_rolling_coeff", "@profit_1200.profit_rolling_coeff.60m",]

[profit_300__profit_rolling_coeff__5m.params]
shift = 300
window = "300s"

[profit_600__profit_rolling_coeff__5m.params]
shift = 600
window = "300s"

[profit_1200__profit_rolling_coeff__5m.params]
shift = 1200
window = "300s"

[profit_300__profit_rolling_coeff__10m.params]
shift = 300
window = "600s"

[profit_600__profit_rolling_coeff__10m.params]
shift = 600
window = "600s"

[profit_1200__profit_rolling_coeff__10m.params]
shift = 1200
window = "600s"

[profit_300__profit_rolling_coeff__15m.params]
shift = 300
window = "900s"

[profit_600__profit_rolling_coeff__15m.params]
shift = 600
window = "900s"

[profit_1200__profit_rolling_coeff__15m.params]
shift = 1200
window = "900s"

[profit_300__profit_rolling_coeff__20m.params]
shift = 300
window = "1200s"

[profit_600__profit_rolling_coeff__20m.params]
shift = 600
window = "1200s"

[profit_1200__profit_rolling_coeff__20m.params]
shift = 1200
window = "1200s"

[profit_300__profit_rolling_coeff__25m.params]
shift = 300
window = "1500s"

[profit_600__profit_rolling_coeff__25m.params]
shift = 600
window = "1500s"

[profit_1200__profit_rolling_coeff__25m.params]
shift = 1200
window = "1500s"

[profit_300__profit_rolling_coeff__30m.params]
shift = 300
window = "1800s"

[profit_600__profit_rolling_coeff__30m.params]
shift = 600
window = "1800s"

[profit_1200__profit_rolling_coeff__30m.params]
shift = 1200
window = "1800s"

[profit_300__profit_rolling_coeff__35m.params]
shift = 300
window = "2100s"

[profit_600__profit_rolling_coeff__35m.params]
shift = 600
window = "2100s"

[profit_1200__profit_rolling_coeff__35m.params]
shift = 1200
window = "2100s"

[profit_300__profit_rolling_coeff__40m.params]
shift = 300
window = "2400s"

[profit_600__profit_rolling_coeff__40m.params]
shift = 600
window = "2400s"

[profit_1200__profit_rolling_coeff__40m.params]
shift = 1200
window = "2400s"

[profit_300__profit_rolling_coeff__45m.params]
shift = 300
window = "2700s"

[profit_600__profit_rolling_coeff__45m.params]
shift = 600
window = "2700s"

[profit_1200__profit_rolling_coeff__45m.params]
shift = 1200
window = "2700s"

[profit_300__profit_rolling_coeff__50m.params]
shift = 300
window = "3000s"

[profit_600__profit_rolling_coeff__50m.params]
shift = 600
window = "3000s"

[profit_1200__profit_rolling_coeff__50m.params]
shift = 1200
window = "3000s"

[profit_300__profit_rolling_coeff__55m.params]
shift = 300
window = "3300s"

[profit_600__profit_rolling_coeff__55m.params]
shift = 600
window = "3300s"

[profit_1200__profit_rolling_coeff__55m.params]
shift = 1200
window = "3300s"

[profit_300__profit_rolling_coeff__60m.params]
shift = 300
window = "3600s"

[profit_600__profit_rolling_coeff__60m.params]
shift = 600
window = "3600s"

[profit_1200__profit_rolling_coeff__60m.params]
shift = 1200
window = "3600s"
