[profit_300__profit_rolling_std__5m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_300", "@profit_rolling_std", "@profit_rolling_std.5m", "@profit_300.profit_rolling_std", "@profit_300.profit_rolling_std.5m",]

[profit_600__profit_rolling_std__5m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_600", "@profit_rolling_std", "@profit_rolling_std.5m", "@profit_600.profit_rolling_std", "@profit_600.profit_rolling_std.5m",]

[profit_1200__profit_rolling_std__5m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_1200", "@profit_rolling_std", "@profit_rolling_std.5m", "@profit_1200.profit_rolling_std", "@profit_1200.profit_rolling_std.5m",]

[profit_300__profit_rolling_std__10m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_300", "@profit_rolling_std", "@profit_rolling_std.10m", "@profit_300.profit_rolling_std", "@profit_300.profit_rolling_std.10m",]

[profit_600__profit_rolling_std__10m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_600", "@profit_rolling_std", "@profit_rolling_std.10m", "@profit_600.profit_rolling_std", "@profit_600.profit_rolling_std.10m",]

[profit_1200__profit_rolling_std__10m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_1200", "@profit_rolling_std", "@profit_rolling_std.10m", "@profit_1200.profit_rolling_std", "@profit_1200.profit_rolling_std.10m",]

[profit_300__profit_rolling_std__15m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_300", "@profit_rolling_std", "@profit_rolling_std.15m", "@profit_300.profit_rolling_std", "@profit_300.profit_rolling_std.15m",]

[profit_600__profit_rolling_std__15m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_600", "@profit_rolling_std", "@profit_rolling_std.15m", "@profit_600.profit_rolling_std", "@profit_600.profit_rolling_std.15m",]

[profit_1200__profit_rolling_std__15m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_1200", "@profit_rolling_std", "@profit_rolling_std.15m", "@profit_1200.profit_rolling_std", "@profit_1200.profit_rolling_std.15m",]

[profit_300__profit_rolling_std__20m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_300", "@profit_rolling_std", "@profit_rolling_std.20m", "@profit_300.profit_rolling_std", "@profit_300.profit_rolling_std.20m",]

[profit_600__profit_rolling_std__20m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_600", "@profit_rolling_std", "@profit_rolling_std.20m", "@profit_600.profit_rolling_std", "@profit_600.profit_rolling_std.20m",]

[profit_1200__profit_rolling_std__20m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_1200", "@profit_rolling_std", "@profit_rolling_std.20m", "@profit_1200.profit_rolling_std", "@profit_1200.profit_rolling_std.20m",]

[profit_300__profit_rolling_std__25m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_300", "@profit_rolling_std", "@profit_rolling_std.25m", "@profit_300.profit_rolling_std", "@profit_300.profit_rolling_std.25m",]

[profit_600__profit_rolling_std__25m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_600", "@profit_rolling_std", "@profit_rolling_std.25m", "@profit_600.profit_rolling_std", "@profit_600.profit_rolling_std.25m",]

[profit_1200__profit_rolling_std__25m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_1200", "@profit_rolling_std", "@profit_rolling_std.25m", "@profit_1200.profit_rolling_std", "@profit_1200.profit_rolling_std.25m",]

[profit_300__profit_rolling_std__30m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_300", "@profit_rolling_std", "@profit_rolling_std.30m", "@profit_300.profit_rolling_std", "@profit_300.profit_rolling_std.30m",]

[profit_600__profit_rolling_std__30m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_600", "@profit_rolling_std", "@profit_rolling_std.30m", "@profit_600.profit_rolling_std", "@profit_600.profit_rolling_std.30m",]

[profit_1200__profit_rolling_std__30m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_1200", "@profit_rolling_std", "@profit_rolling_std.30m", "@profit_1200.profit_rolling_std", "@profit_1200.profit_rolling_std.30m",]

[profit_300__profit_rolling_std__35m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_300", "@profit_rolling_std", "@profit_rolling_std.35m", "@profit_300.profit_rolling_std", "@profit_300.profit_rolling_std.35m",]

[profit_600__profit_rolling_std__35m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_600", "@profit_rolling_std", "@profit_rolling_std.35m", "@profit_600.profit_rolling_std", "@profit_600.profit_rolling_std.35m",]

[profit_1200__profit_rolling_std__35m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_1200", "@profit_rolling_std", "@profit_rolling_std.35m", "@profit_1200.profit_rolling_std", "@profit_1200.profit_rolling_std.35m",]

[profit_300__profit_rolling_std__40m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_300", "@profit_rolling_std", "@profit_rolling_std.40m", "@profit_300.profit_rolling_std", "@profit_300.profit_rolling_std.40m",]

[profit_600__profit_rolling_std__40m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_600", "@profit_rolling_std", "@profit_rolling_std.40m", "@profit_600.profit_rolling_std", "@profit_600.profit_rolling_std.40m",]

[profit_1200__profit_rolling_std__40m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_1200", "@profit_rolling_std", "@profit_rolling_std.40m", "@profit_1200.profit_rolling_std", "@profit_1200.profit_rolling_std.40m",]

[profit_300__profit_rolling_std__45m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_300", "@profit_rolling_std", "@profit_rolling_std.45m", "@profit_300.profit_rolling_std", "@profit_300.profit_rolling_std.45m",]

[profit_600__profit_rolling_std__45m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_600", "@profit_rolling_std", "@profit_rolling_std.45m", "@profit_600.profit_rolling_std", "@profit_600.profit_rolling_std.45m",]

[profit_1200__profit_rolling_std__45m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_1200", "@profit_rolling_std", "@profit_rolling_std.45m", "@profit_1200.profit_rolling_std", "@profit_1200.profit_rolling_std.45m",]

[profit_300__profit_rolling_std__50m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_300", "@profit_rolling_std", "@profit_rolling_std.50m", "@profit_300.profit_rolling_std", "@profit_300.profit_rolling_std.50m",]

[profit_600__profit_rolling_std__50m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_600", "@profit_rolling_std", "@profit_rolling_std.50m", "@profit_600.profit_rolling_std", "@profit_600.profit_rolling_std.50m",]

[profit_1200__profit_rolling_std__50m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_1200", "@profit_rolling_std", "@profit_rolling_std.50m", "@profit_1200.profit_rolling_std", "@profit_1200.profit_rolling_std.50m",]

[profit_300__profit_rolling_std__55m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_300", "@profit_rolling_std", "@profit_rolling_std.55m", "@profit_300.profit_rolling_std", "@profit_300.profit_rolling_std.55m",]

[profit_600__profit_rolling_std__55m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_600", "@profit_rolling_std", "@profit_rolling_std.55m", "@profit_600.profit_rolling_std", "@profit_600.profit_rolling_std.55m",]

[profit_1200__profit_rolling_std__55m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_1200", "@profit_rolling_std", "@profit_rolling_std.55m", "@profit_1200.profit_rolling_std", "@profit_1200.profit_rolling_std.55m",]

[profit_300__profit_rolling_std__60m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_300", "@profit_rolling_std", "@profit_rolling_std.60m", "@profit_300.profit_rolling_std", "@profit_300.profit_rolling_std.60m",]

[profit_600__profit_rolling_std__60m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_600", "@profit_rolling_std", "@profit_rolling_std.60m", "@profit_600.profit_rolling_std", "@profit_600.profit_rolling_std.60m",]

[profit_1200__profit_rolling_std__60m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_std"
tags = [ "@profit_1200", "@profit_rolling_std", "@profit_rolling_std.60m", "@profit_1200.profit_rolling_std", "@profit_1200.profit_rolling_std.60m",]

[profit_300__profit_rolling_std__5m.params]
shift = 300
window = "300s"

[profit_600__profit_rolling_std__5m.params]
shift = 600
window = "300s"

[profit_1200__profit_rolling_std__5m.params]
shift = 1200
window = "300s"

[profit_300__profit_rolling_std__10m.params]
shift = 300
window = "600s"

[profit_600__profit_rolling_std__10m.params]
shift = 600
window = "600s"

[profit_1200__profit_rolling_std__10m.params]
shift = 1200
window = "600s"

[profit_300__profit_rolling_std__15m.params]
shift = 300
window = "900s"

[profit_600__profit_rolling_std__15m.params]
shift = 600
window = "900s"

[profit_1200__profit_rolling_std__15m.params]
shift = 1200
window = "900s"

[profit_300__profit_rolling_std__20m.params]
shift = 300
window = "1200s"

[profit_600__profit_rolling_std__20m.params]
shift = 600
window = "1200s"

[profit_1200__profit_rolling_std__20m.params]
shift = 1200
window = "1200s"

[profit_300__profit_rolling_std__25m.params]
shift = 300
window = "1500s"

[profit_600__profit_rolling_std__25m.params]
shift = 600
window = "1500s"

[profit_1200__profit_rolling_std__25m.params]
shift = 1200
window = "1500s"

[profit_300__profit_rolling_std__30m.params]
shift = 300
window = "1800s"

[profit_600__profit_rolling_std__30m.params]
shift = 600
window = "1800s"

[profit_1200__profit_rolling_std__30m.params]
shift = 1200
window = "1800s"

[profit_300__profit_rolling_std__35m.params]
shift = 300
window = "2100s"

[profit_600__profit_rolling_std__35m.params]
shift = 600
window = "2100s"

[profit_1200__profit_rolling_std__35m.params]
shift = 1200
window = "2100s"

[profit_300__profit_rolling_std__40m.params]
shift = 300
window = "2400s"

[profit_600__profit_rolling_std__40m.params]
shift = 600
window = "2400s"

[profit_1200__profit_rolling_std__40m.params]
shift = 1200
window = "2400s"

[profit_300__profit_rolling_std__45m.params]
shift = 300
window = "2700s"

[profit_600__profit_rolling_std__45m.params]
shift = 600
window = "2700s"

[profit_1200__profit_rolling_std__45m.params]
shift = 1200
window = "2700s"

[profit_300__profit_rolling_std__50m.params]
shift = 300
window = "3000s"

[profit_600__profit_rolling_std__50m.params]
shift = 600
window = "3000s"

[profit_1200__profit_rolling_std__50m.params]
shift = 1200
window = "3000s"

[profit_300__profit_rolling_std__55m.params]
shift = 300
window = "3300s"

[profit_600__profit_rolling_std__55m.params]
shift = 600
window = "3300s"

[profit_1200__profit_rolling_std__55m.params]
shift = 1200
window = "3300s"

[profit_300__profit_rolling_std__60m.params]
shift = 300
window = "3600s"

[profit_600__profit_rolling_std__60m.params]
shift = 600
window = "3600s"

[profit_1200__profit_rolling_std__60m.params]
shift = 1200
window = "3600s"
