[profit_300__profit_rolling_stochastic__5m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_300", "@profit_rolling_stochastic", "@profit_rolling_stochastic.5m", "@profit_300.profit_rolling_stochastic", "@profit_300.profit_rolling_stochastic.5m",]

[profit_600__profit_rolling_stochastic__5m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_600", "@profit_rolling_stochastic", "@profit_rolling_stochastic.5m", "@profit_600.profit_rolling_stochastic", "@profit_600.profit_rolling_stochastic.5m",]

[profit_1200__profit_rolling_stochastic__5m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_1200", "@profit_rolling_stochastic", "@profit_rolling_stochastic.5m", "@profit_1200.profit_rolling_stochastic", "@profit_1200.profit_rolling_stochastic.5m",]

[profit_300__profit_rolling_stochastic__10m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_300", "@profit_rolling_stochastic", "@profit_rolling_stochastic.10m", "@profit_300.profit_rolling_stochastic", "@profit_300.profit_rolling_stochastic.10m",]

[profit_600__profit_rolling_stochastic__10m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_600", "@profit_rolling_stochastic", "@profit_rolling_stochastic.10m", "@profit_600.profit_rolling_stochastic", "@profit_600.profit_rolling_stochastic.10m",]

[profit_1200__profit_rolling_stochastic__10m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_1200", "@profit_rolling_stochastic", "@profit_rolling_stochastic.10m", "@profit_1200.profit_rolling_stochastic", "@profit_1200.profit_rolling_stochastic.10m",]

[profit_300__profit_rolling_stochastic__15m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_300", "@profit_rolling_stochastic", "@profit_rolling_stochastic.15m", "@profit_300.profit_rolling_stochastic", "@profit_300.profit_rolling_stochastic.15m",]

[profit_600__profit_rolling_stochastic__15m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_600", "@profit_rolling_stochastic", "@profit_rolling_stochastic.15m", "@profit_600.profit_rolling_stochastic", "@profit_600.profit_rolling_stochastic.15m",]

[profit_1200__profit_rolling_stochastic__15m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_1200", "@profit_rolling_stochastic", "@profit_rolling_stochastic.15m", "@profit_1200.profit_rolling_stochastic", "@profit_1200.profit_rolling_stochastic.15m",]

[profit_300__profit_rolling_stochastic__20m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_300", "@profit_rolling_stochastic", "@profit_rolling_stochastic.20m", "@profit_300.profit_rolling_stochastic", "@profit_300.profit_rolling_stochastic.20m",]

[profit_600__profit_rolling_stochastic__20m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_600", "@profit_rolling_stochastic", "@profit_rolling_stochastic.20m", "@profit_600.profit_rolling_stochastic", "@profit_600.profit_rolling_stochastic.20m",]

[profit_1200__profit_rolling_stochastic__20m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_1200", "@profit_rolling_stochastic", "@profit_rolling_stochastic.20m", "@profit_1200.profit_rolling_stochastic", "@profit_1200.profit_rolling_stochastic.20m",]

[profit_300__profit_rolling_stochastic__25m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_300", "@profit_rolling_stochastic", "@profit_rolling_stochastic.25m", "@profit_300.profit_rolling_stochastic", "@profit_300.profit_rolling_stochastic.25m",]

[profit_600__profit_rolling_stochastic__25m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_600", "@profit_rolling_stochastic", "@profit_rolling_stochastic.25m", "@profit_600.profit_rolling_stochastic", "@profit_600.profit_rolling_stochastic.25m",]

[profit_1200__profit_rolling_stochastic__25m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_1200", "@profit_rolling_stochastic", "@profit_rolling_stochastic.25m", "@profit_1200.profit_rolling_stochastic", "@profit_1200.profit_rolling_stochastic.25m",]

[profit_300__profit_rolling_stochastic__30m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_300", "@profit_rolling_stochastic", "@profit_rolling_stochastic.30m", "@profit_300.profit_rolling_stochastic", "@profit_300.profit_rolling_stochastic.30m",]

[profit_600__profit_rolling_stochastic__30m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_600", "@profit_rolling_stochastic", "@profit_rolling_stochastic.30m", "@profit_600.profit_rolling_stochastic", "@profit_600.profit_rolling_stochastic.30m",]

[profit_1200__profit_rolling_stochastic__30m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_1200", "@profit_rolling_stochastic", "@profit_rolling_stochastic.30m", "@profit_1200.profit_rolling_stochastic", "@profit_1200.profit_rolling_stochastic.30m",]

[profit_300__profit_rolling_stochastic__35m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_300", "@profit_rolling_stochastic", "@profit_rolling_stochastic.35m", "@profit_300.profit_rolling_stochastic", "@profit_300.profit_rolling_stochastic.35m",]

[profit_600__profit_rolling_stochastic__35m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_600", "@profit_rolling_stochastic", "@profit_rolling_stochastic.35m", "@profit_600.profit_rolling_stochastic", "@profit_600.profit_rolling_stochastic.35m",]

[profit_1200__profit_rolling_stochastic__35m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_1200", "@profit_rolling_stochastic", "@profit_rolling_stochastic.35m", "@profit_1200.profit_rolling_stochastic", "@profit_1200.profit_rolling_stochastic.35m",]

[profit_300__profit_rolling_stochastic__40m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_300", "@profit_rolling_stochastic", "@profit_rolling_stochastic.40m", "@profit_300.profit_rolling_stochastic", "@profit_300.profit_rolling_stochastic.40m",]

[profit_600__profit_rolling_stochastic__40m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_600", "@profit_rolling_stochastic", "@profit_rolling_stochastic.40m", "@profit_600.profit_rolling_stochastic", "@profit_600.profit_rolling_stochastic.40m",]

[profit_1200__profit_rolling_stochastic__40m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_1200", "@profit_rolling_stochastic", "@profit_rolling_stochastic.40m", "@profit_1200.profit_rolling_stochastic", "@profit_1200.profit_rolling_stochastic.40m",]

[profit_300__profit_rolling_stochastic__45m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_300", "@profit_rolling_stochastic", "@profit_rolling_stochastic.45m", "@profit_300.profit_rolling_stochastic", "@profit_300.profit_rolling_stochastic.45m",]

[profit_600__profit_rolling_stochastic__45m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_600", "@profit_rolling_stochastic", "@profit_rolling_stochastic.45m", "@profit_600.profit_rolling_stochastic", "@profit_600.profit_rolling_stochastic.45m",]

[profit_1200__profit_rolling_stochastic__45m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_1200", "@profit_rolling_stochastic", "@profit_rolling_stochastic.45m", "@profit_1200.profit_rolling_stochastic", "@profit_1200.profit_rolling_stochastic.45m",]

[profit_300__profit_rolling_stochastic__50m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_300", "@profit_rolling_stochastic", "@profit_rolling_stochastic.50m", "@profit_300.profit_rolling_stochastic", "@profit_300.profit_rolling_stochastic.50m",]

[profit_600__profit_rolling_stochastic__50m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_600", "@profit_rolling_stochastic", "@profit_rolling_stochastic.50m", "@profit_600.profit_rolling_stochastic", "@profit_600.profit_rolling_stochastic.50m",]

[profit_1200__profit_rolling_stochastic__50m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_1200", "@profit_rolling_stochastic", "@profit_rolling_stochastic.50m", "@profit_1200.profit_rolling_stochastic", "@profit_1200.profit_rolling_stochastic.50m",]

[profit_300__profit_rolling_stochastic__55m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_300", "@profit_rolling_stochastic", "@profit_rolling_stochastic.55m", "@profit_300.profit_rolling_stochastic", "@profit_300.profit_rolling_stochastic.55m",]

[profit_600__profit_rolling_stochastic__55m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_600", "@profit_rolling_stochastic", "@profit_rolling_stochastic.55m", "@profit_600.profit_rolling_stochastic", "@profit_600.profit_rolling_stochastic.55m",]

[profit_1200__profit_rolling_stochastic__55m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_1200", "@profit_rolling_stochastic", "@profit_rolling_stochastic.55m", "@profit_1200.profit_rolling_stochastic", "@profit_1200.profit_rolling_stochastic.55m",]

[profit_300__profit_rolling_stochastic__60m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_300", "@profit_rolling_stochastic", "@profit_rolling_stochastic.60m", "@profit_300.profit_rolling_stochastic", "@profit_300.profit_rolling_stochastic.60m",]

[profit_600__profit_rolling_stochastic__60m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_600", "@profit_rolling_stochastic", "@profit_rolling_stochastic.60m", "@profit_600.profit_rolling_stochastic", "@profit_600.profit_rolling_stochastic.60m",]

[profit_1200__profit_rolling_stochastic__60m]
columns = [ "bid_price", "ask_price",]
module = "features.scripts.profit_rolling_stochastic"
tags = [ "@profit_1200", "@profit_rolling_stochastic", "@profit_rolling_stochastic.60m", "@profit_1200.profit_rolling_stochastic", "@profit_1200.profit_rolling_stochastic.60m",]

[profit_300__profit_rolling_stochastic__5m.params]
shift = 300
window = "300s"

[profit_600__profit_rolling_stochastic__5m.params]
shift = 600
window = "300s"

[profit_1200__profit_rolling_stochastic__5m.params]
shift = 1200
window = "300s"

[profit_300__profit_rolling_stochastic__10m.params]
shift = 300
window = "600s"

[profit_600__profit_rolling_stochastic__10m.params]
shift = 600
window = "600s"

[profit_1200__profit_rolling_stochastic__10m.params]
shift = 1200
window = "600s"

[profit_300__profit_rolling_stochastic__15m.params]
shift = 300
window = "900s"

[profit_600__profit_rolling_stochastic__15m.params]
shift = 600
window = "900s"

[profit_1200__profit_rolling_stochastic__15m.params]
shift = 1200
window = "900s"

[profit_300__profit_rolling_stochastic__20m.params]
shift = 300
window = "1200s"

[profit_600__profit_rolling_stochastic__20m.params]
shift = 600
window = "1200s"

[profit_1200__profit_rolling_stochastic__20m.params]
shift = 1200
window = "1200s"

[profit_300__profit_rolling_stochastic__25m.params]
shift = 300
window = "1500s"

[profit_600__profit_rolling_stochastic__25m.params]
shift = 600
window = "1500s"

[profit_1200__profit_rolling_stochastic__25m.params]
shift = 1200
window = "1500s"

[profit_300__profit_rolling_stochastic__30m.params]
shift = 300
window = "1800s"

[profit_600__profit_rolling_stochastic__30m.params]
shift = 600
window = "1800s"

[profit_1200__profit_rolling_stochastic__30m.params]
shift = 1200
window = "1800s"

[profit_300__profit_rolling_stochastic__35m.params]
shift = 300
window = "2100s"

[profit_600__profit_rolling_stochastic__35m.params]
shift = 600
window = "2100s"

[profit_1200__profit_rolling_stochastic__35m.params]
shift = 1200
window = "2100s"

[profit_300__profit_rolling_stochastic__40m.params]
shift = 300
window = "2400s"

[profit_600__profit_rolling_stochastic__40m.params]
shift = 600
window = "2400s"

[profit_1200__profit_rolling_stochastic__40m.params]
shift = 1200
window = "2400s"

[profit_300__profit_rolling_stochastic__45m.params]
shift = 300
window = "2700s"

[profit_600__profit_rolling_stochastic__45m.params]
shift = 600
window = "2700s"

[profit_1200__profit_rolling_stochastic__45m.params]
shift = 1200
window = "2700s"

[profit_300__profit_rolling_stochastic__50m.params]
shift = 300
window = "3000s"

[profit_600__profit_rolling_stochastic__50m.params]
shift = 600
window = "3000s"

[profit_1200__profit_rolling_stochastic__50m.params]
shift = 1200
window = "3000s"

[profit_300__profit_rolling_stochastic__55m.params]
shift = 300
window = "3300s"

[profit_600__profit_rolling_stochastic__55m.params]
shift = 600
window = "3300s"

[profit_1200__profit_rolling_stochastic__55m.params]
shift = 1200
window = "3300s"

[profit_300__profit_rolling_stochastic__60m.params]
shift = 300
window = "3600s"

[profit_600__profit_rolling_stochastic__60m.params]
shift = 600
window = "3600s"

[profit_1200__profit_rolling_stochastic__60m.params]
shift = 1200
window = "3600s"
