[spread_rolling_q50__5m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_q50"
tags = [ "@spread_rolling_q50", "@spread_rolling_q50.5m",]

[spread_rolling_q50__10m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_q50"
tags = [ "@spread_rolling_q50", "@spread_rolling_q50.5m",]

[spread_rolling_q50__15m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_q50"
tags = [ "@spread_rolling_q50", "@spread_rolling_q50.5m",]

[spread_rolling_q50__20m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_q50"
tags = [ "@spread_rolling_q50", "@spread_rolling_q50.5m",]

[spread_rolling_q50__25m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_q50"
tags = [ "@spread_rolling_q50", "@spread_rolling_q50.5m",]

[spread_rolling_q50__30m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_q50"
tags = [ "@spread_rolling_q50", "@spread_rolling_q50.5m",]

[spread_rolling_q50__35m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_q50"
tags = [ "@spread_rolling_q50", "@spread_rolling_q50.5m",]

[spread_rolling_q50__40m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_q50"
tags = [ "@spread_rolling_q50", "@spread_rolling_q50.5m",]

[spread_rolling_q50__45m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_q50"
tags = [ "@spread_rolling_q50", "@spread_rolling_q50.5m",]

[spread_rolling_q50__50m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_q50"
tags = [ "@spread_rolling_q50", "@spread_rolling_q50.5m",]

[spread_rolling_q50__55m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_q50"
tags = [ "@spread_rolling_q50", "@spread_rolling_q50.5m",]

[spread_rolling_q50__60m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_q50"
tags = [ "@spread_rolling_q50", "@spread_rolling_q50.5m",]

[spread_rolling_q50__5m.params]
window = "300s"

[spread_rolling_q50__10m.params]
window = "600s"

[spread_rolling_q50__15m.params]
window = "900s"

[spread_rolling_q50__20m.params]
window = "1200s"

[spread_rolling_q50__25m.params]
window = "1500s"

[spread_rolling_q50__30m.params]
window = "1800s"

[spread_rolling_q50__35m.params]
window = "2100s"

[spread_rolling_q50__40m.params]
window = "2400s"

[spread_rolling_q50__45m.params]
window = "2700s"

[spread_rolling_q50__50m.params]
window = "3000s"

[spread_rolling_q50__55m.params]
window = "3300s"

[spread_rolling_q50__60m.params]
window = "3600s"
