[spread_rolling_var__5m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_var"
tags = [ "@spread_rolling_var", "@spread_rolling_var.5m",]

[spread_rolling_var__10m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_var"
tags = [ "@spread_rolling_var", "@spread_rolling_var.5m",]

[spread_rolling_var__15m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_var"
tags = [ "@spread_rolling_var", "@spread_rolling_var.5m",]

[spread_rolling_var__20m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_var"
tags = [ "@spread_rolling_var", "@spread_rolling_var.5m",]

[spread_rolling_var__25m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_var"
tags = [ "@spread_rolling_var", "@spread_rolling_var.5m",]

[spread_rolling_var__30m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_var"
tags = [ "@spread_rolling_var", "@spread_rolling_var.5m",]

[spread_rolling_var__35m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_var"
tags = [ "@spread_rolling_var", "@spread_rolling_var.5m",]

[spread_rolling_var__40m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_var"
tags = [ "@spread_rolling_var", "@spread_rolling_var.5m",]

[spread_rolling_var__45m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_var"
tags = [ "@spread_rolling_var", "@spread_rolling_var.5m",]

[spread_rolling_var__50m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_var"
tags = [ "@spread_rolling_var", "@spread_rolling_var.5m",]

[spread_rolling_var__55m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_var"
tags = [ "@spread_rolling_var", "@spread_rolling_var.5m",]

[spread_rolling_var__60m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_var"
tags = [ "@spread_rolling_var", "@spread_rolling_var.5m",]

[spread_rolling_var__5m.params]
window = "300s"

[spread_rolling_var__10m.params]
window = "600s"

[spread_rolling_var__15m.params]
window = "900s"

[spread_rolling_var__20m.params]
window = "1200s"

[spread_rolling_var__25m.params]
window = "1500s"

[spread_rolling_var__30m.params]
window = "1800s"

[spread_rolling_var__35m.params]
window = "2100s"

[spread_rolling_var__40m.params]
window = "2400s"

[spread_rolling_var__45m.params]
window = "2700s"

[spread_rolling_var__50m.params]
window = "3000s"

[spread_rolling_var__55m.params]
window = "3300s"

[spread_rolling_var__60m.params]
window = "3600s"
