[spread_rolling_std__5m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_std"
tags = [ "@spread_rolling_std", "@spread_rolling_std.5m",]

[spread_rolling_std__10m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_std"
tags = [ "@spread_rolling_std", "@spread_rolling_std.5m",]

[spread_rolling_std__15m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_std"
tags = [ "@spread_rolling_std", "@spread_rolling_std.5m",]

[spread_rolling_std__20m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_std"
tags = [ "@spread_rolling_std", "@spread_rolling_std.5m",]

[spread_rolling_std__25m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_std"
tags = [ "@spread_rolling_std", "@spread_rolling_std.5m",]

[spread_rolling_std__30m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_std"
tags = [ "@spread_rolling_std", "@spread_rolling_std.5m",]

[spread_rolling_std__35m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_std"
tags = [ "@spread_rolling_std", "@spread_rolling_std.5m",]

[spread_rolling_std__40m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_std"
tags = [ "@spread_rolling_std", "@spread_rolling_std.5m",]

[spread_rolling_std__45m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_std"
tags = [ "@spread_rolling_std", "@spread_rolling_std.5m",]

[spread_rolling_std__50m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_std"
tags = [ "@spread_rolling_std", "@spread_rolling_std.5m",]

[spread_rolling_std__55m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_std"
tags = [ "@spread_rolling_std", "@spread_rolling_std.5m",]

[spread_rolling_std__60m]
columns = [ "ask_price", "bid_price",]
module = "features.scripts.spread_rolling_std"
tags = [ "@spread_rolling_std", "@spread_rolling_std.5m",]

[spread_rolling_std__5m.params]
window = "300s"

[spread_rolling_std__10m.params]
window = "600s"

[spread_rolling_std__15m.params]
window = "900s"

[spread_rolling_std__20m.params]
window = "1200s"

[spread_rolling_std__25m.params]
window = "1500s"

[spread_rolling_std__30m.params]
window = "1800s"

[spread_rolling_std__35m.params]
window = "2100s"

[spread_rolling_std__40m.params]
window = "2400s"

[spread_rolling_std__45m.params]
window = "2700s"

[spread_rolling_std__50m.params]
window = "3000s"

[spread_rolling_std__55m.params]
window = "3300s"

[spread_rolling_std__60m.params]
window = "3600s"
